[tool.black]
line-length = 88
target-version = ["py39"]

[tool.ruff]
line-length = 88
target-version = "py39"
select = ["E", "F", "W", "I", "N", "D", "UP", "B", "A", "C", "T", "PIE", "PLC", "PLE", "PLW", "RUF"]
ignore = [
    "D100", # Missing docstring in public module
    "D104", # Missing docstring in public package
    "D105", # Missing docstring in magic method
    "D107", # Missing docstring in __init__
    "D203", # 1 blank line required before class docstring
    "D213", # Multi-line docstring should start on the second line
    "D406", # Section name should end with a colon
    "D407", # Missing dashed underline after section header
    "D413", # Missing blank line after last section
    "E501", # Line too long (handled by Black)
]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
"tests/**.py" = ["D"]
